In [60]:
from numpy import mean
from numpy import std
from pandas import read_csv
import pandas as pd
from numpy import absolute
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [61]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.csv'
dataframe = read_csv(url, header=None)
data = dataframe.values

In [64]:
X, y = data[:, :-1], data[:, -1]
print(X.shape, y.shape)

(506, 13) (506,)

In [65]:
cv = LeaveOneOut()
model = RandomForestRegressor(random_state=1)

In [68]:
cross_val_score?

In [69]:
scores = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
scores = absolute(scores)

In [72]:
scores

array([5.0300e+00, 1.2520e+00, 1.0500e-01, 1.1870e+00, 2.0980e+00,
       5.1560e+00, 2.7600e+00, 9.6870e+00, 2.0060e+00, 2.2500e-01,
       5.9110e+00, 1.5930e+00, 3.0700e-01, 6.3500e-01, 1.5670e+00,
       3.7000e-01, 1.5360e+00, 7.8100e-01, 1.7130e+00, 1.5990e+00,
       1.0420e+00, 1.2110e+00, 6.0100e-01, 9.9600e-01, 1.1810e+00,
       1.6510e+00, 8.7300e-01, 3.1700e-01, 1.7870e+00, 2.4750e+00,
       2.0370e+00, 5.1990e+00, 3.0290e+00, 1.4290e+00, 1.1150e+00,
       2.1250e+00, 8.6700e-01, 3.3300e-01, 3.7470e+00, 2.8180e+00,
       1.2250e+00, 4.4430e+00, 9.6100e-01, 1.6700e-01, 6.6900e-01,
       4.3400e-01, 1.1500e-01, 3.0290e+00, 4.3040e+00, 3.4800e-01,
       1.1840e+00, 1.5510e+00, 4.2900e-01, 2.9960e+00, 3.8500e-01,
       1.4720e+00, 1.8240e+00, 7.4200e-01, 3.9500e-01, 7.8900e-01,
       2.2000e-01, 2.8700e+00, 1.9280e+00, 8.1800e-01, 6.3000e-01,
       1.4700e+00, 8.1600e-01, 1.7110e+00, 1.7730e+00, 4.5000e-02,
       3.9900e-01, 3.5600e-01, 2.8600e-01, 5.7300e-01, 9.0000e-02,
       1.7050e+00, 9.5400e-01, 7.6400e-01, 4.4700e-01, 9.9500e-01,
       1.0170e+00, 2.2170e+00, 1.5040e+00, 5.5600e-01, 1.7270e+00,
       2.1100e-01, 1.6370e+00, 7.6000e-02, 7.5030e+00, 3.2790e+00,
       2.4300e-01, 4.7400e-01, 1.4000e-01, 3.6900e-01, 1.0840e+00,
       1.1650e+00, 7.9500e-01, 6.6240e+00, 1.2760e+00, 1.0050e+00,
       2.6650e+00, 1.1900e-01, 8.5000e-01, 6.9700e-01, 9.7000e-02,
       3.7000e-02, 1.2410e+00, 9.2900e-01, 6.3000e-01, 3.6900e-01,
       1.2660e+00, 2.3600e+00, 5.4300e-01, 5.1600e-01, 2.8080e+00,
       7.2500e-01, 8.8900e-01, 7.0800e-01, 1.6320e+00, 5.7200e-01,
       8.3700e-01, 1.2040e+00, 1.5720e+00, 2.0600e-01, 5.9800e-01,
       2.3290e+00, 1.0340e+00, 1.3900e-01, 9.4400e-01, 1.8580e+00,
       4.6500e-01, 6.4200e-01, 3.4050e+00, 1.1590e+00, 5.1000e-02,
       8.8100e-01, 8.6600e-01, 1.1980e+00, 2.2570e+00, 2.7190e+00,
       1.5110e+00, 4.7500e-01, 1.2580e+00, 1.8550e+00, 2.8210e+00,
       1.0130e+00, 6.8500e-01, 3.8500e-01, 4.1410e+00, 6.0800e-01,
       1.7480e+00, 7.7200e-01, 5.7390e+00, 3.5610e+00, 3.3100e-01,
       2.2730e+00, 3.4430e+00, 1.1273e+01, 8.4500e-01, 4.4240e+00,
       1.8190e+00, 5.4980e+00, 2.7900e+00, 1.4560e+00, 2.0670e+00,
       2.9500e+00, 1.1670e+00, 3.5930e+00, 1.9550e+00, 1.0000e-01,
       2.8920e+00, 2.9080e+00, 3.5270e+00, 7.6800e-01, 1.6670e+00,
       2.6020e+00, 9.6600e-01, 6.5700e-01, 1.7180e+00, 3.9310e+00,
       4.3050e+00, 1.0599e+01, 2.3210e+00, 3.1620e+00, 2.7640e+00,
       4.1840e+00, 8.3100e+00, 4.6100e+00, 9.8900e-01, 8.0900e-01,
       6.7070e+00, 1.1870e+00, 1.3910e+00, 1.6090e+00, 3.7600e-01,
       2.4820e+00, 1.1200e+00, 1.6790e+00, 1.5130e+00, 2.6720e+00,
       1.8660e+00, 1.3080e+00, 4.8590e+00, 5.6300e-01, 2.0640e+00,
       2.1000e-02, 1.9030e+00, 3.2180e+00, 3.3330e+00, 2.2370e+00,
       1.8400e+00, 5.9000e-02, 1.0310e+00, 4.4670e+00, 5.5920e+00,
       1.2610e+00, 2.2620e+00, 4.9980e+00, 1.3970e+00, 7.3800e-01,
       2.0080e+00, 3.4540e+00, 1.3370e+00, 4.2230e+00, 1.7390e+00,
       7.7220e+00, 8.5890e+00, 9.4300e-01, 2.9980e+00, 2.0460e+00,
       3.1550e+00, 8.1800e-01, 3.6060e+00, 3.9780e+00, 2.9700e+00,
       1.5100e+00, 1.8330e+00, 1.5000e+00, 4.1800e-01, 2.7530e+00,
       5.4440e+00, 1.4800e+00, 6.1100e-01, 4.7100e-01, 7.2700e-01,
       1.0940e+00, 2.8910e+00, 3.0800e-01, 1.6560e+00, 9.4000e-02,
       7.5000e-02, 1.4040e+00, 2.6360e+00, 2.2590e+00, 8.4400e-01,
       1.2190e+00, 2.7470e+00, 3.3490e+00, 1.3120e+00, 4.7000e-02,
       1.1210e+00, 8.8700e-01, 2.7640e+00, 3.9600e-01, 2.7840e+00,
       1.2570e+00, 4.6950e+00, 4.8550e+00, 2.4440e+00, 5.3700e-01,
       4.8000e-02, 3.5300e-01, 9.5000e-01, 8.2840e+00, 1.6060e+00,
       5.7600e-01, 1.4930e+00, 1.8470e+00, 4.5610e+00, 4.3500e+00,
       1.3610e+00, 1.4380e+00, 4.1100e-01, 4.2220e+00, 1.1750e+00,
       3.6600e-01, 2.4460e+00, 6.8000e-02, 9.8300e-01, 6.0500e-01,
       2.9610e+00, 3.7450e+00, 5.8900e-01, 1.4700e+00, 2.0000e-02,
       1.8780e+00, 1.2210e+00, 7.8700e-01, 1.8400e+00, 4.5580e+00,
       4.6570e+00, 3.4540e+00, 3.2620e+00, 4.6200e-01, 2.9040e+00,
       1.6750e+00, 1.3420e+00, 1.9400e+00, 7.0120e+00, 3.5200e-01,
       4.2400e+00, 2.0200e+00, 5.6700e-01, 9.4800e-01, 3.7800e-01,
       3.4430e+00, 1.3110e+00, 3.4100e-01, 8.0100e-01, 6.2600e-01,
       2.7200e-01, 9.1000e-01, 1.4710e+00, 5.9500e-01, 1.4700e+00,
       2.5600e-01, 1.2300e+00, 1.3510e+00, 1.4180e+00, 9.0100e-01,
       2.1440e+00, 2.1860e+00, 1.1840e+00, 8.3100e-01, 2.8740e+00,
       1.0990e+00, 1.5300e-01, 1.2540e+00, 4.6000e-01, 1.1040e+00,
       1.4080e+00, 4.0100e-01, 7.6210e+00, 3.6200e+00, 4.0600e-01,
       2.7480e+00, 1.6350e+00, 8.8300e-01, 2.8020e+00, 1.3300e+00,
       5.5000e-01, 2.1270e+00, 2.8400e+00, 1.8700e-01, 1.4510e+00,
       1.0290e+00, 3.2520e+00, 9.0200e-01, 1.6620e+00, 1.7760e+00,
       2.6270e+00, 8.5100e-01, 3.1000e-02, 1.8390e+00, 2.1424e+01,
       5.6930e+00, 2.3120e+00, 4.2320e+00, 1.3436e+01, 8.9510e+00,
       1.3763e+01, 1.0087e+01, 8.9350e+00, 1.9350e+00, 2.4790e+00,
       1.5124e+01, 2.5020e+00, 5.5000e-01, 2.4460e+00, 1.6600e+00,
       9.6880e+00, 4.1000e-02, 3.4500e-01, 1.6690e+00, 6.0000e-02,
       2.1940e+00, 3.5650e+00, 1.2960e+00, 1.6740e+00, 3.0000e-03,
       9.5400e-01, 8.0490e+00, 5.2700e-01, 1.5560e+00, 1.4820e+00,
       1.0580e+00, 1.9900e+00, 4.2650e+00, 1.9090e+00, 4.9150e+00,
       3.2050e+00, 3.8580e+00, 1.0270e+00, 3.2580e+00, 1.1200e+00,
       4.4980e+00, 1.0490e+00, 6.2700e+00, 2.6660e+00, 9.6400e+00,
       1.2973e+01, 1.5870e+00, 4.5220e+00, 2.0330e+00, 1.9620e+00,
       1.7140e+00, 2.5870e+00, 2.4850e+00, 2.3400e-01, 4.6120e+00,
       2.6510e+00, 1.8890e+00, 6.1400e-01, 3.6600e-01, 3.5660e+00,
       1.4200e+00, 5.6290e+00, 4.6810e+00, 1.9530e+00, 2.0680e+00,
       6.9400e-01, 7.0060e+00, 5.1310e+00, 1.4040e+00, 2.0020e+00,
       1.9340e+00, 2.8860e+00, 5.9700e-01, 3.5400e-01, 1.0810e+00,
       7.2100e-01, 3.7240e+00, 2.9760e+00, 1.1700e+00, 2.4300e-01,
       9.3700e-01, 1.2700e-01, 3.0230e+00, 5.0300e-01, 1.8620e+00,
       1.4420e+00, 6.9200e-01, 1.9300e-01, 5.6980e+00, 1.3470e+00,
       7.9500e-01, 2.9990e+00, 2.2110e+00, 3.0900e-01, 2.9610e+00,
       9.4600e-01, 1.2290e+00, 1.1730e+00, 1.5710e+00, 1.4900e-01,
       9.4500e-01, 4.4410e+00, 5.0820e+00, 5.1690e+00, 2.5310e+00,
       1.8410e+00, 1.4220e+00, 4.1770e+00, 4.4090e+00, 6.9600e-01,
       1.8980e+00, 6.7000e-01, 1.9460e+00, 1.4100e-01, 1.2830e+00,
       1.9910e+00, 4.2670e+00, 5.6640e+00, 1.5170e+00, 6.8300e-01,
       6.6900e-01, 4.2000e-02, 6.3600e-01, 1.2390e+00, 5.8810e+00,
       2.7650e+00, 2.2540e+00, 6.9000e-02, 2.2850e+00, 3.7470e+00,
       3.9530e+00, 1.1600e+00, 1.7400e+00, 2.9700e-01, 2.3470e+00,
       3.4580e+00, 1.4140e+00, 1.8570e+00, 3.3640e+00, 3.8710e+00,
       8.6910e+00])

In [70]:
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 2.182 (2.338)

# StratifiedKFOLD

In [73]:
df_aug = pd.read_csv("aug_train.csv", sep = ",")
df_aug

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [74]:
y = df_aug['target'].to_numpy()

for n in df_aug.columns:
  if str(df_aug[n].dtype) == 'object' or str(df_aug[n].dtype) == 'category':
    df_aug[n] = df_aug[n].astype('category').cat.codes
X = df_aug.drop(['target'], axis=1).to_numpy()
df_aug.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,5,0.920,1,0,2,0,5,21,-1,-1,0,36,1.0
1,29725,77,0.776,1,1,2,0,5,6,4,5,4,47,0.0
2,11561,64,0.624,-1,1,0,0,5,15,-1,-1,5,83,0.0
3,33241,14,0.789,-1,1,-1,0,1,20,-1,5,5,52,1.0
4,666,50,0.767,1,0,2,2,5,21,4,1,3,8,0.0

In [ ]:
from sklearn.model_selection import StratifiedKFold
import numpy as np

skf_aug = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)
train, test = list(skf_aug.split(X, y))[0]
X_train = X[train]
X_test = X[test]
y_train = y[train]
y_test= y[test]

In [82]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

t_aug = DecisionTreeClassifier()
par_aug = list(np.arange(0.0, 1., step=0.05))
cv_aug = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)
tunner_aug = GridSearchCV(estimator=t_aug, param_grid={'ccp_alpha':par_aug}, cv=cv_aug)
_=tunner_aug.fit(X, y)

In [84]:
print('Train score StratifiedKFold: ' + str(tunner_aug.score(X, y)))
#print('Test score StratifiedKFold: ' + str(tunner_aug.score(X_test, y_test)))

Train score StratifiedKFold: 0.7823363607892264

In [ ]:
from sklearn.model_selection import KFold
KFold_aug= KFold(n_splits=5, random_state=0, shuffle=True)
train_2, test_2 = list(KFold_aug.split(X))[0]
X_train_2 = X[train_2]
X_test_2 = X[test_2]
y_train_2 = y[train_2]
y_test_2 = y[test_2]

In [ ]:
t_aug2 = DecisionTreeClassifier()
par_aug2 = list(np.arange(0.0, 1., step=0.05))
cv_aug2 = KFold(n_splits=5, random_state=0, shuffle=True)
tunner_aug2 = GridSearchCV(estimator=t_aug2, param_grid={'ccp_alpha':par_aug2}, cv=cv_aug2)
_=tunner_aug2.fit(X_train_2, y_train_2)

In [ ]:
print('Train score KFold: ' + str(tunner_aug2.score(X_train_2, y_train_2)))
print('Test score KFold: ' + str(tunner_aug2.score(X_test_2, y_test_2)))

In [ ]:
df = pd.read_csv("Life_Expectancy_Data.csv", sep = ",")
df.head()

In [ ]:
df.rename(columns={'Life expectancy ':'Life_expectancy','Adult Mortality':'Adult_Mortality','infant deaths': 'infant_deaths','percentage expenditure':'percentage_expenditure','Hepatitis B':'Hepatitis_B','Measles ':'Measles',' BMI ':'BMI', 'under-five deaths ':'under_five_deaths', 'Total expenditure':'Total_expenditure', 'Diphtheria ': 'Diphtheria',' HIV/AIDS':'HIV/AIDS', ' thinness  1-19 years':'thinness_1_19_years',' thinness 5-9 years':'thinness_5_9_years','Income composition of resources':'Income_composition_of_resources'}, inplace=True)

In [ ]:
df = df.dropna()

In [ ]:
y = df['Life_expectancy'].to_numpy() 

for n in df.columns:
  if str(df[n].dtype) == 'object' or str(df[n].dtype) == 'category':
    df[n] = df[n].astype('category').cat.codes
X = df.drop(['Life_expectancy'], axis=1).to_numpy()
df.head()

In [ ]:
from sklearn.model_selection import KFold
KFold = KFold(n_splits=5, random_state=0, shuffle=True)
train, test = list(KFold.split(X))[0]
X_train = X[train]
X_test = X[test]
y_train = y[train]
y_test = y[test]

In [ ]:
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
t = DecisionTreeRegressor()
par = list(np.arange(0.0, 1., step=0.05))
cv = KFold(n_splits=5, random_state=0, shuffle=True)
tunner = GridSearchCV(estimator=t, param_grid={'ccp_alpha':par}, cv=cv)
_=tunner.fit(X_train, y_train)

In [ ]:
print('Train score KFold Tree: ' + str(tunner.score(X_train, y_train)))
print('Test score KFold Tree: ' + str(tunner.score(X_test, y_test)))

# GridSearch, RandomSearch

In [85]:
import pandas as pd
import numpy as np
import scipy as sp

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [86]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [87]:
df = pd.DataFrame(np.c_[data['data'], data['target']],
                  columns= np.append(data['feature_names'], ['target']))

In [88]:
features= list(df.columns[0:10])
features

['mean radius',
 'mean texture',
 'mean perimeter',
 'mean area',
 'mean smoothness',
 'mean compactness',
 'mean concavity',
 'mean concave points',
 'mean symmetry',
 'mean fractal dimension']

In [89]:
data = df[features + ['target']]
data.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,0.0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.0

In [90]:
X = data.drop(['target'],axis=1)
y = data['target']

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [92]:
knn = KNeighborsClassifier()

In [93]:
knn?

In [95]:
param_grid = {'n_neighbors':np.arange(1, 10),
              'weights': ['uniform', 'distance'], 
              'leaf_size':[1,3,5,7,10],
              'algorithm':['auto', 'kd_tree']}

model = GridSearchCV(knn, param_grid=param_grid, cv=5)

In [98]:
GridSearchCV?

In [96]:
model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'kd_tree'],
                         'leaf_size': [1, 3, 5, 7, 10],
                         'n_neighbors': array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
                         'weights': ['uniform', 'distance']})

In [97]:
print("Mejores parametros: "+str(model.best_params_))
print("Mejor Score: "+str(model.best_score_)+'\n')

Mejores parametros: {'algorithm': 'auto', 'leaf_size': 1, 'n_neighbors': 6, 'weights': 'distance'}
Mejor Score: 0.8849247606019152

In [99]:
scores = pd.DataFrame(model.cv_results_)
scores

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_leaf_size,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002200,4.000426e-04,0.002801,7.485576e-04,auto,1,1,uniform,"{'algorithm': 'auto', 'leaf_size': 1, 'n_neigh...",0.895349,0.858824,0.858824,0.823529,0.800000,0.847305,0.032792,141
1,0.002001,3.989506e-07,0.001800,4.000187e-04,auto,1,1,distance,"{'algorithm': 'auto', 'leaf_size': 1, 'n_neigh...",0.895349,0.858824,0.858824,0.823529,0.800000,0.847305,0.032792,141
2,0.001801,4.001623e-04,0.003601,4.895515e-04,auto,1,2,uniform,"{'algorithm': 'auto', 'leaf_size': 1, 'n_neigh...",0.895349,0.835294,0.847059,0.835294,0.811765,0.844952,0.027685,171
3,0.002024,4.993316e-05,0.001576,5.214801e-04,auto,1,2,distance,"{'algorithm': 'auto', 'leaf_size': 1, 'n_neigh...",0.895349,0.858824,0.858824,0.823529,0.800000,0.847305,0.032792,141
4,0.002401,4.897655e-04,0.003201,4.004242e-04,auto,1,3,uniform,"{'algorithm': 'auto', 'leaf_size': 1, 'n_neigh...",0.895349,0.894118,0.941176,0.811765,0.870588,0.882599,0.042162,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,0.001600,4.899598e-04,0.001400,4.901739e-04,kd_tree,10,7,distance,"{'algorithm': 'kd_tree', 'leaf_size': 10, 'n_n...",0.895349,0.882353,0.941176,0.823529,0.858824,0.880246,0.039040,51
176,0.001800,4.001142e-04,0.003401,4.905438e-04,kd_tree,10,8,uniform,"{'algorithm': 'kd_tree', 'leaf_size': 10, 'n_n...",0.860465,0.870588,0.905882,0.823529,0.870588,0.866211,0.026332,121
177,0.001600,4.899014e-04,0.001401,4.909339e-04,kd_tree,10,8,distance,"{'algorithm': 'kd_tree', 'leaf_size': 10, 'n_n...",0.895349,0.882353,0.941176,0.823529,0.870588,0.882599,0.038020,11
178,0.001801,4.003289e-04,0.003000,2.431402e-07,kd_tree,10,9,uniform,"{'algorithm': 'kd_tree', 'leaf_size': 10, 'n_n...",0.883721,0.870588,0.941176,0.823529,0.870588,0.877921,0.037685,61
179,0.002001,1.784161e-07,0.001200,4.000664e-04,kd_tree,10,9,distance,"{'algorithm': 'kd_tree', 'leaf_size': 10, 'n_n...",0.883721,0.882353,0.941176,0.823529,0.870588,0.880274,0.037521,41

In [101]:
prediction = model.predict(X_test)

In [102]:
print('Exactitud:', accuracy_score(y_test, prediction))

Exactitud: 0.9090909090909091

In [103]:
cm = confusion_matrix(y_test,prediction)
print("Matriz de confusión:")
print(cm)

Matriz de confusión:
[[47  7]
 [ 6 83]]

In [104]:
param_dist = {'n_neighbors':sp.stats.randint(1, 10),
              'weights': ['uniform', 'distance'], 
              'leaf_size':sp.stats.randint(1, 10),
              'algorithm':['auto', 'kd_tree']}

model = RandomizedSearchCV(knn, param_dist,n_iter=100, random_state=0, cv=5)

In [105]:
model.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=100,
                   param_distributions={'algorithm': ['auto', 'kd_tree'],
                                        'leaf_size': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002882EDC8348>,
                                        'n_neighbors': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002882EDC8A08>,
                                        'weights': ['uniform', 'distance']},
                   random_state=0)

In [106]:
print("Mejores parametros: "+str(model.best_params_))
print("Mejor Score: "+str(model.best_score_)+'\n')

Mejores parametros: {'algorithm': 'kd_tree', 'leaf_size': 7, 'n_neighbors': 6, 'weights': 'distance'}
Mejor Score: 0.8849247606019152

In [107]:
scores = pd.DataFrame(model.cv_results_)
scores

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_leaf_size,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001400,4.901156e-04,0.001601,4.891628e-04,auto,6,1,distance,"{'algorithm': 'auto', 'leaf_size': 6, 'n_neigh...",0.895349,0.858824,0.858824,0.823529,0.800000,0.847305,0.032792,83
1,0.002001,2.431402e-07,0.001400,4.901544e-04,kd_tree,4,8,distance,"{'algorithm': 'kd_tree', 'leaf_size': 4, 'n_ne...",0.895349,0.882353,0.941176,0.823529,0.870588,0.882599,0.038020,4
2,0.001800,4.000187e-04,0.003001,9.536743e-08,kd_tree,6,3,uniform,"{'algorithm': 'kd_tree', 'leaf_size': 6, 'n_ne...",0.895349,0.894118,0.941176,0.811765,0.870588,0.882599,0.042162,4
3,0.001601,4.902128e-04,0.003001,3.504023e-07,kd_tree,7,9,uniform,"{'algorithm': 'kd_tree', 'leaf_size': 7, 'n_ne...",0.883721,0.870588,0.941176,0.823529,0.870588,0.877921,0.037685,32
4,0.002000,1.784161e-07,0.001800,7.487489e-04,auto,2,7,distance,"{'algorithm': 'auto', 'leaf_size': 2, 'n_neigh...",0.895349,0.882353,0.941176,0.823529,0.858824,0.880246,0.039040,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.002201,3.999710e-04,0.003001,2.431402e-07,kd_tree,1,1,uniform,"{'algorithm': 'kd_tree', 'leaf_size': 1, 'n_ne...",0.895349,0.858824,0.858824,0.823529,0.800000,0.847305,0.032792,83
96,0.001600,4.900766e-04,0.002801,3.999711e-04,auto,4,2,uniform,"{'algorithm': 'auto', 'leaf_size': 4, 'n_neigh...",0.895349,0.835294,0.847059,0.835294,0.811765,0.844952,0.027685,99
97,0.001401,4.903298e-04,0.001600,4.902325e-04,kd_tree,7,7,distance,"{'algorithm': 'kd_tree', 'leaf_size': 7, 'n_ne...",0.895349,0.882353,0.941176,0.823529,0.858824,0.880246,0.039040,28
98,0.001400,4.899598e-04,0.003001,1.168008e-07,auto,9,8,uniform,"{'algorithm': 'auto', 'leaf_size': 9, 'n_neigh...",0.860465,0.870588,0.905882,0.823529,0.870588,0.866211,0.026332,71
99,0.001800,3.998756e-04,0.001200,4.000664e-04,auto,7,9,distance,"{'algorithm': 'auto', 'leaf_size': 7, 'n_neigh...",0.883721,0.882353,0.941176,0.823529,0.870588,0.880274,0.037521,23

In [108]:
prediction = model.predict(X_test)

In [109]:
print('Exactitud:', accuracy_score(y_test, prediction))

Exactitud: 0.9090909090909091

In [110]:
cm = confusion_matrix(y_test,prediction)
print("Matriz de confusión:")
print(cm)

Matriz de confusión:
[[47  7]
 [ 6 83]]